#!/bin/bash

$CMAKE_BIN \
    -DBUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
    -B $ROOT_BUILD_DIR \
    -S $ROOT_REPOSITORY_DIR
$CMAKE_BIN \
    --build \
    $ROOT_BUILD_DIR
$CMAKE_BIN \
    -DCMAKE_INSTALL_PREFIX=$ROOT_INSTALL_DIR \
    -P $ROOT_BUILD_DIR/cmake_install.cmake
