name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        tool: [
          clang_debug,
          clang_release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install clang compiler
        run: sudo bash .github/workflows/install_clang.sh

      - name: Configure
        run: cmake -S . -B .build -DCMAKE_TOOLCHAIN_FILE="toolchain/${{ matrix.tool }}.cmake"

      - name: Build
        run: cmake --build .build --parallel 8
