name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install snap
      run: sudo bash scripts/install_snap.sh

    - name: Install compiler
      run: sudo bash .github/workflows/install_compiler.sh

    - name: Build
      run: CMAKE_BIN="snap run cmake" bash build.sh
